export const awardsData = [
  {
    id: 1,
    title: "ET Shark Awards",
    desc: "Best non-profit campaign award for impactful initiatives supporting underprivileged children and communit ",
    year: 2024,
    image: "About/Award/1.jpg",
  },
  {
    id: 2,
    title: "Social Media for Empowerment",
    desc: "Recognised for excellence in advocacy and communication through digital platforms for social empowerment.",
    year: 2021,
    image: "About/Award/2.jpg",
  },
  {
    id: 3,
    title: "Kaleido Awards",
    desc: "Best campaign in Not-for-Profit category for innovative storytelling and social impact.",
    year: 2021,
  image: "About/Award/3.jpg",
  },
  {
    id: 4,
    title: "ACEF Global Awards",
    desc: "Social Media Brand of the Year for outstanding audience engagement and digital reach.",
    year: 2020,
  image: "About/Award/4.png",
  },
  {
    id: 5,
    title: "India NGO Excellence Award",
    desc: "Honoured for long-term contribution towards education, healthcare, and child development programs.",
    year: 2019,
     image: "About/Award/5.png",
  },
  {
    id: 6,
    title: "National Social Impact Award",
    desc: "Awarded for driving measurable change in vulnerable communities across multiple regions in India.",
    year: 2018,
     image: "About/Award/5.png",
  },
  {
    id: 7,
    title: "CSR Leadership Award",
    desc: "Recognised for strong partnerships with corporate organisations to deliver sustainable CSR initiatives.",
    year: 2017,
     image: "About/Award/6.jpg",
  },
  {
    id: 8,
    title: "Child Welfare Achievement Award",
    desc: "Awarded for exceptional work in protecting child rights and improving access to education.",
    year: 2016,
    image: "About/Award/7.png",
  },
  {
    id: 9,
    title: "Healthcare Initiative Award",
    desc: "Recognised for impactful healthcare programs benefiting rural and underprivileged populations.",
    year: 2015,
   image: "About/Award/8.jpg",
  },
  {
    id: 10,
    title: "Education Support Excellence Award",
    desc: "Honoured for strengthening educational infrastructure and supporting quality learning outcomes.",
    year: 2014,
   image: "About/Award/9.jpg",
  },
  {
    id: 11,
    title: "Women Empowerment Award",
    desc: "Recognised for initiatives promoting women leadership, skill development, and social inclusion.",
    year: 2013,
   image: "About/Award/10.jpg",
  },
  {
    id: 12,
    title: "Environmental Sustainability Award",
    desc: "Awarded for environmental awareness campaigns and sustainable community practices.",
    year: 2012,
     image: "About/Award/11.png",
  },
  {
    id: 13,
    title: "Community Development Award",
    desc: "Honoured for holistic community development through education, healthcare, and livelihood programs.",
    year: 2011,
   image: "About/Award/12.jpg",
  },
  {
    id: 14,
    title: "National Recognition for Social Service",
    desc: "Recognised at the national level for consistent contribution towards social transformation.",
    year: 2010,
    image: "About/Award/13.png",
  },
  {
    id: 15,
    title: "Lifetime Contribution Award",
    desc: "Honoured for decades of unwavering commitment towards social justice and humanitarian causes.",
    year: 2009,
    image: "About/Award/14.png",
  },
];
